// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNSQ06ODmdYECl0Bu48uIY2t689lssork',
    appId: '1:401121736356:web:88800e42d941267e5f5831',
    messagingSenderId: '401121736356',
    projectId: 'eartheyefinalyearproject',
    authDomain: 'eartheyefinalyearproject.firebaseapp.com',
    storageBucket: 'eartheyefinalyearproject.firebasestorage.app',
    measurementId: 'G-J65DY8X075',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV_0Ks_tRJC70jt3ZB8HOPK5esWr9bbaw',
    appId: '1:401121736356:android:13f1b26733c3163b5f5831',
    messagingSenderId: '401121736356',
    projectId: 'eartheyefinalyearproject',
    storageBucket: 'eartheyefinalyearproject.firebasestorage.app',
  );
}
